services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: areyouhigh/my-portfolio:latest
    container_name: my-portfolio
    ports:
      - '8081:80'
    restart: always
